### ISSUE TITLE
讨论基础框架， node.js +  react + mongodb 部署使用 Docker

### ISSUE THREAD

**Issue by carlos-wong** [carlos-wong/Bug_Hunter#1]

**Comment by carlos-wong** [comment]
需要找一个项目的模板，应用上然后开始制作第一个界面

**Comment by carlos-wong** [comment]
@all 这是一个爱好项目。欢迎大家踊跃参与

**Comment by carlos-wong** [comment]
有想要邀请的朋友也可以加入

**Comment by wangshub** [comment]
@carlos-wong 贤哥，我最近也是在想这个事儿！

**Comment by wangshub** [comment]
https://github.com/chentsulin/electron-react-boilerplate

**Comment by carlos-wong** [comment]
@wangshub 这个是客户端的框架。我们还是做一个网页吧

**Comment by wangshub** [comment]
OK ~ @carlos-wong

**Comment by carlos-wong** [comment]
@wangshub 截至日期下周一前，我们选择一个框架 init :)

**Comment by wangshub** [comment]
好的 @carlos-wong

**Comment by wangshub** [comment]
https://github.com/wx1993/Node-React-MongoDB-TodoList

**Comment by wangshub** [comment]
https://github.com/levittlili/react-note

**Comment by carlos-wong** [comment]
https://github.com/react-boilerplate/react-boilerplate @wangshub 我们选一个基础的框架吧。这样我们有一个坚实的基础可以添加功能。 我今天会先安装一下这个框架看跑起来的效果。我建议有以下几个标准：

1. 方便调试，并且是热更新
2. 部署方便，特别是打包之后运行程序
3. 框架完整，基本的中间件及事件驱动的设计都已经实现

**Comment by wangshub** [comment]
感觉主要的框架应该是 react 这块，后端的请求和数据库都比较成熟了吧 @carlos-wong

**Comment by carlos-wong** [comment]
@wangshub 是的，但是我们这个项目应该是其他人拉取下来后端也部署好，可以开发也可以直接使用。所以后端的代码也要实现

**Comment by carlos-wong** [comment]
@wangshub 我看了一下这个框架，后端的服务其实也有。我们只要接入数据库

**Comment by wangshub** [comment]
那我也装起来跑一下 @carlos-wong

**Comment by carlos-wong** [comment]
@wangshub 我会添加一个 docker-compose.yml。 目标是直接使用 docker 启动调试和部署。

**Comment by carlos-wong** [comment]
https://github.com/carlos-wong/Bug_Hunter/pull/2 已完成。
